version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-database
    environment:
     POSTGRES_DB: exe-database
     POSTGRES_USER: abiswas 
     POSTGRES_PASSWORD: ab123
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: abiswas@cn.com
      PGADMIN_DEFAULT_PASSWORD: ab123
    ports:
      - "5050:80"
    networks:
      - pg-network

networks:
  pg-network:

volumes:
  pg-data:
